# Generated by Django 4.2.2 on 2023-06-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart_item',
            new_name='CartItem',
        ),
    ]
